language: ruby

rvm:
  - "2.6.3"

before_install:
  - gem i bundler -v 1.17.3
  - gem i rake

cache: bundler

bundler_args: --without development --jobs=3 --retry=3 --path=../vendor/bundle

script: bundle exec rake test --trace
